import {AAVE_POOL,ethCall,encAddress,decodeWords} from './base.js';
export const DATA_PROVIDER='0x0F43731EB8d45A581f4a36DD74F5f358bc90C73A';
export const ORACLE='0x2Cc0Fc26eD4563A5ce5e8bdcfe1A2878676Ae156';
const GET_RESERVES_LIST='0xd1946dbc',GET_USER_EMODE='0xeddf1b79',GET_USER_RESERVE_DATA='0x28dd2d01',GET_RESERVE_CONFIG='0x3e150141',GET_LIQUIDATION_PROTOCOL_FEE='0x3cb8a622',GET_FLASH_LOAN_ENABLED='0xd7ed3ef4',GET_ASSET_PRICE='0xb3596f07',BASE_CURRENCY_UNIT='0x8c89b64f';
function addrWord(w){return '0x'+BigInt(w).toString(16).padStart(64,'0').slice(-40)}function enc2(a,b){return encAddress(a)+encAddress(b)}
export function formatUnits(value,decimals){const n=BigInt(value),d=BigInt(decimals),base=10n**d,whole=n/base,frac=(n%base).toString().padStart(Number(d),'0').replace(/0+$/,'');return frac?`${whole}.${frac}`:`${whole}`}
export function formatByUnit(value,unit){const u=BigInt(unit);if(u<=0n)return String(value);const s=u.toString();if(/^10*$/.test(s))return formatUnits(BigInt(value),s.length-1);return `${value}/${unit}`}
export async function reservesList(block='latest'){const{result}=await ethCall(AAVE_POOL,GET_RESERVES_LIST,block);const w=decodeWords(result);if(w.length<2)return[];const offset=Number(w[0]/32n),count=Number(w[offset]||0n),out=[];for(let i=0;i<count;i++)out.push(addrWord(w[offset+1+i]).toLowerCase());return out}
export async function userEMode(user,block='latest'){const{result}=await ethCall(AAVE_POOL,GET_USER_EMODE+encAddress(user),block);const w=decodeWords(result);return w.length?Number(w[0]):0}
export async function userReserveData(asset,user,block='latest'){const{result}=await ethCall(DATA_PROVIDER,GET_USER_RESERVE_DATA+enc2(asset,user),block);const w=decodeWords(result);if(w.length<9)throw new Error('short getUserReserveData');return{a_token_balance:w[0],stable_debt:w[1],variable_debt:w[2],scaled_variable_debt:w[4],liquidity_rate:w[6],collateral_enabled:w[8]!==0n,total_debt:w[1]+w[2]}}
export async function reserveConfig(asset,block='latest'){const{result}=await ethCall(DATA_PROVIDER,GET_RESERVE_CONFIG+encAddress(asset),block);const w=decodeWords(result);if(w.length<10)throw new Error('short getReserveConfigurationData');return{decimals:Number(w[0]),ltv_bps:Number(w[1]),liquidation_threshold_bps:Number(w[2]),liquidation_bonus_bps:Number(w[3]),reserve_factor_bps:Number(w[4]),usage_as_collateral_enabled:w[5]!==0n,borrowing_enabled:w[6]!==0n,is_active:w[8]!==0n,is_frozen:w[9]!==0n}}
export async function liquidationProtocolFee(asset,block='latest'){const{result}=await ethCall(DATA_PROVIDER,GET_LIQUIDATION_PROTOCOL_FEE+encAddress(asset),block);const w=decodeWords(result);return w.length?Number(w[0]):null}
export async function flashLoanEnabled(asset,block='latest'){const{result}=await ethCall(DATA_PROVIDER,GET_FLASH_LOAN_ENABLED+encAddress(asset),block);const w=decodeWords(result);return w.length?w[0]!==0n:false}
export async function assetPrice(asset,block='latest'){const{result}=await ethCall(ORACLE,GET_ASSET_PRICE+encAddress(asset),block);const w=decodeWords(result);return w.length?w[0]:0n}
export async function baseCurrencyUnit(block='latest'){const{result}=await ethCall(ORACLE,BASE_CURRENCY_UNIT,block);const w=decodeWords(result);return w.length?w[0]:1n}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;try{out[i]=await fn(items[i])}catch(e){out[i]={asset:items[i],error:String(e?.message||e)}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
export async function userPositions(user,block='latest'){const[assets,emode,baseUnit]=await Promise.all([reservesList(block),userEMode(user,block),baseCurrencyUnit(block)]);const basic=await mapLimit(assets,8,async asset=>({asset,...await userReserveData(asset,user,block)}));const active=basic.filter(x=>!x.error&&(x.a_token_balance>0n||x.total_debt>0n));const enriched=await mapLimit(active,6,async row=>{const[cfg,fee,price,flash]=await Promise.all([reserveConfig(row.asset,block),liquidationProtocolFee(row.asset,block),assetPrice(row.asset,block),flashLoanEnabled(row.asset,block)]);const unit=10n**BigInt(cfg.decimals),collBase=row.a_token_balance*price/unit,debtBase=row.total_debt*price/unit;return{asset:row.asset,decimals:cfg.decimals,a_token_balance_raw:row.a_token_balance.toString(),a_token_balance:formatUnits(row.a_token_balance,cfg.decimals),debt_raw:row.total_debt.toString(),debt:formatUnits(row.total_debt,cfg.decimals),collateral_enabled:row.collateral_enabled,oracle_price_raw:price.toString(),collateral_value_base_raw:collBase.toString(),collateral_value_base:formatByUnit(collBase,baseUnit),debt_value_base_raw:debtBase.toString(),debt_value_base:formatByUnit(debtBase,baseUnit),liquidation_bonus_bps:cfg.liquidation_bonus_bps,liquidation_protocol_fee_bps:fee,flash_loan_enabled:flash,ltv_bps:cfg.ltv_bps,liquidation_threshold_bps:cfg.liquidation_threshold_bps,is_active:cfg.is_active,is_frozen:cfg.is_frozen}});return{user:user.toLowerCase(),block,e_mode_category:emode,base_currency_unit:baseUnit.toString(),positions:enriched.filter(x=>!x.error),errors:enriched.filter(x=>x.error)}}
