import{rpc,batchRpc,hexInt,BASE_RPCS}from'../lib/rpc.js';
const POOL='0xA238Dd80C259a72e81d7e4664a9801593F98d1c5';
const BORROW_TOPIC='0xb3d084820fb1a9decffb176436bd02558d15fac9b0ddfed8c465bc7359d7dce0';
const USER_SELECTOR='bf92857c';
const ONE=1000000000000000000n;
const padAddr=a=>'0'.repeat(24)+a.toLowerCase().replace(/^0x/,'');
function account(hex){const h=(hex||'0x').replace(/^0x/,'');if(h.length<384)return null;const w=[];for(let i=0;i<6;i++)w.push(BigInt('0x'+h.slice(i*64,(i+1)*64)));if(w[1]===0n)return null;return{collateral_base_raw:w[0].toString(),debt_base_raw:w[1].toString(),available_base_raw:w[2].toString(),liq_threshold_bps:Number(w[3]),ltv_bps:Number(w[4]),hf_1e18:w[5].toString(),hf:Number(w[5])/1e18,liquidatable_exact:w[5]>0n&&w[5]<ONE};}
async function score(users,url,tag='latest'){const calls=users.map(u=>({method:'eth_call',params:[{to:POOL,data:'0x'+USER_SELECTOR+padAddr(u)},tag]}));const out=await batchRpc(url,calls,10000);const rows=[];out.forEach((x,i)=>{if(!x||x.error)return;const a=account(x.result);if(a)rows.push({user:users[i],...a});});return rows;}
export default async function handler(req,res){const started=Date.now();try{const head=await rpc('eth_blockNumber');const latest=hexInt(head.result);const requested=Number(req.query?.window||2500);const window=Math.min(Math.max(Number.isFinite(requested)?requested:2500,200),6000);const from=Math.max(0,latest-window+1);let logs=[];for(let b=from;b<=latest;b+=1000){const e=Math.min(latest,b+999);const q=await rpc('eth_getLogs',[{address:POOL,fromBlock:'0x'+b.toString(16),toBlock:'0x'+e.toString(16),topics:[BORROW_TOPIC]}]);logs.push(...(q.result||[]));}
const last=new Map();for(const g of logs){const t=g.topics||[];if(t.length<3)continue;const h=t[2].replace(/^0x/,'');if(h.length!==64)continue;const user='0x'+h.slice(-40);const bn=hexInt(g.blockNumber||'0x0');if(bn>=(last.get(user)||0))last.set(user,bn);}const users=[...last.entries()].sort((a,b)=>b[1]-a[1]).slice(0,120).map(x=>x[0]);let rows=[];for(let i=0;i<users.length;i+=30)rows.push(...await score(users.slice(i,i+30),head.rpc,'latest'));rows.sort((a,b)=>a.hf-b.hf);const liquidatable=rows.filter(x=>x.liquidatable_exact);
const secondary=BASE_RPCS.find(x=>x!==head.rpc)||BASE_RPCS[0];let verified=[];if(liquidatable.length){const p=await score(liquidatable.map(x=>x.user),secondary,'pending');const pm=new Map(p.map(x=>[x.user.toLowerCase(),x]));verified=liquidatable.map(x=>{const y=pm.get(x.user.toLowerCase());return{...x,pending_hf:y?.hf??null,pending_hf_1e18:y?.hf_1e18??null,verification_rpc:secondary,verified_liquidatable:!!y&&y.liquidatable_exact};}).filter(x=>x.verified_liquidatable);}
res.setHeader('cache-control','no-store');res.status(200).json({ok:true,chain_id:8453,block_number:latest,rpc:head.rpc,observed_at:new Date().toISOString(),window_blocks:window,borrow_events:logs.length,unique_recent_borrowers:users.length,accounts_scored:rows.length,liquidatable_latest:liquidatable,verified_liquidatable_now:verified,near:rows.filter(x=>x.hf>0&&x.hf<1.12).slice(0,25),lowest:rows.slice(0,25),verification:{policy:'DUAL_RPC_LATEST_PLUS_PENDING_EXACT_UINT256',primary_rpc:head.rpc,secondary_rpc:secondary,requires_both_hf_1e18_lt:'1000000000000000000'},evidence:{pool:POOL,borrow_topic:BORROW_TOPIC,user_selector:'0x'+USER_SELECTOR},elapsed_ms:Date.now()-started});}catch(e){res.status(502).json({ok:false,error:String(e?.message||e),observed_at:new Date().toISOString(),elapsed_ms:Date.now()-started});}}
