const RPCS=['https://mainnet-preconf.base.org','https://mainnet.base.org','https://base-rpc.publicnode.com'];
const POOL='0xA238Dd80C259a72e81d7e4664a9801593F98d1c5';
const DATA_PROVIDER='0x0F43731EB8d45A581f4a36DD74F5f358bc90C73A';
const ORACLE='0x2Cc0Fc26eD4563A5ce5e8bdcfe1A2878676Ae156';
const SEL={reserves:'d1946dbc',userReserve:'28dd2d01',reserveConfig:'3e150141',assetPrice:'b3596f07',baseUnit:'8c89b64f',protocolFee:'3cb8a622',account:'bf92857c'};
function addr(a){const h=String(a).toLowerCase().replace(/^0x/,'');if(!/^[0-9a-f]{40}$/.test(h))throw new Error('invalid address');return h.padStart(64,'0');}
function words(data){const h=String(data||'0x').replace(/^0x/,'');const o=[];for(let i=0;i+64<=h.length;i+=64)o.push(BigInt('0x'+h.slice(i,i+64)));return o;}
export function decodeAddressArray(data){const w=words(data);if(w.length<2)throw new Error('short address[]');const off=Number(w[0]/32n);if(!Number.isSafeInteger(off)||off<0||off>=w.length)throw new Error('bad address[] offset');const n=Number(w[off]);if(!Number.isSafeInteger(n)||n<0||off+1+n>w.length)throw new Error('bad address[] length');return w.slice(off+1,off+1+n).map(x=>'0x'+x.toString(16).padStart(64,'0').slice(-40));}
function decAccount(data){const w=words(data);if(w.length<6)throw new Error('short account');return{total_collateral_base:w[0],total_debt_base:w[1],health_factor:w[5]};}
export function decUserReserve(data){const w=words(data);if(w.length<9)throw new Error('short user reserve');return{a_token:w[0],stable_debt:w[1],variable_debt:w[2],collateral_enabled:w[8]!==0n};}
export function decConfig(data){const w=words(data);if(w.length<10)throw new Error('short config');return{decimals:Number(w[0]),ltv_bps:Number(w[1]),liquidation_threshold_bps:Number(w[2]),liquidation_bonus_bps:Number(w[3]),reserve_factor_bps:Number(w[4]),collateral_enabled:w[5]!==0n,borrowing_enabled:w[6]!==0n,active:w[8]!==0n,frozen:w[9]!==0n};}
function one(data){const w=words(data);if(!w.length)throw new Error('short uint');return w[0];}
function fmt(raw,dec=18,places=8){const neg=raw<0n;let x=neg?-raw:raw;const d=10n**BigInt(dec);const a=x/d,b=(x%d).toString().padStart(dec,'0').slice(0,places).replace(/0+$/,'');return(neg?'-':'')+a.toString()+(b?'.'+b:'');}
function valueBase(amount,price,decimals){return amount*price/(10n**BigInt(decimals));}
async function post(url,payload,timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:c.signal,cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(t);}}
async function any(method,params=[],timeout=12000){const es=[];for(const url of RPCS){try{const j=await post(url,{jsonrpc:'2.0',id:1,method,params},timeout);if(j.error)throw new Error(j.error.message||JSON.stringify(j.error));return{result:j.result,url};}catch(e){es.push(url+':'+String(e?.message||e));}}throw new Error('all RPCs failed: '+es.join(' | '));}
async function batch(calls,timeout=20000){const es=[];for(const url of RPCS){try{const p=calls.map((x,i)=>({jsonrpc:'2.0',id:i+1,method:'eth_call',params:[x,'latest']}));const j=await post(url,p,timeout);if(!Array.isArray(j))throw new Error('batch response not array');const m=new Map(j.map(x=>[x.id,x]));return{rows:calls.map((_,i)=>m.get(i+1)||{error:{message:'missing'}}),url};}catch(e){es.push(url+':'+String(e?.message||e));}}throw new Error('all batch RPCs failed: '+es.join(' | '));}
export default async function handler(req,res){res.setHeader('cache-control','no-store');const started=Date.now();try{const user=String(req.query?.user||req.query?.address||'').toLowerCase();if(!/^0x[0-9a-f]{40}$/.test(user))return res.status(400).json({ok:false,error:'valid user/address required'});const[rl,au,bu]=await Promise.all([any('eth_call',[{to:POOL,data:'0x'+SEL.reserves},'latest']),any('eth_call',[{to:POOL,data:'0x'+SEL.account+addr(user)},'latest']),any('eth_call',[{to:ORACLE,data:'0x'+SEL.baseUnit},'latest'])]);const reserves=decodeAddressArray(rl.result);const account=decAccount(au.result);const baseUnit=one(bu.result);const calls=[];for(const a of reserves){calls.push({to:DATA_PROVIDER,data:'0x'+SEL.userReserve+addr(a)+addr(user)});calls.push({to:DATA_PROVIDER,data:'0x'+SEL.reserveConfig+addr(a)});calls.push({to:DATA_PROVIDER,data:'0x'+SEL.protocolFee+addr(a)});calls.push({to:ORACLE,data:'0x'+SEL.assetPrice+addr(a)});}const b=await batch(calls);const positions=[];for(let i=0;i<reserves.length;i++){const x=b.rows.slice(i*4,i*4+4);if(x.some(y=>y?.error||!y?.result))continue;try{const u=decUserReserve(x[0].result),c=decConfig(x[1].result),fee=one(x[2].result),price=one(x[3].result);const debt=u.stable_debt+u.variable_debt;if(u.a_token===0n&&debt===0n)continue;const cv=valueBase(u.a_token,price,c.decimals),dv=valueBase(debt,price,c.decimals);const grossBonusBps=Math.max(0,c.liquidation_bonus_bps-10000);const protocolFeeBps=Number(fee);const effectiveBonusBps=grossBonusBps*(10000-protocolFeeBps)/10000;positions.push({asset:reserves[i],decimals:c.decimals,a_token_balance_raw:u.a_token.toString(),a_token_balance:fmt(u.a_token,c.decimals),stable_debt_raw:u.stable_debt.toString(),variable_debt_raw:u.variable_debt.toString(),total_debt_raw:debt.toString(),total_debt:fmt(debt,c.decimals),collateral_enabled_on_user:u.collateral_enabled,oracle_price_raw:price.toString(),collateral_value_base_raw:cv.toString(),debt_value_base_raw:dv.toString(),liquidation_bonus_bps:c.liquidation_bonus_bps,gross_bonus_bps:grossBonusBps,liquidation_protocol_fee_bps:protocolFeeBps,effective_bonus_bps_estimate:effectiveBonusBps,ltv_bps:c.ltv_bps,liquidation_threshold_bps:c.liquidation_threshold_bps,active:c.active,frozen:c.frozen});}catch{}}
positions.sort((a,b)=>Number(BigInt(b.debt_value_base_raw)-BigInt(a.debt_value_base_raw)));const debts=positions.filter(x=>BigInt(x.total_debt_raw)>0n);const collaterals=positions.filter(x=>x.collateral_enabled_on_user&&BigInt(x.a_token_balance_raw)>0n&&x.liquidation_bonus_bps>10000);res.status(200).json({ok:true,version:'AAVE-LIQ-LEGS-V1',observed_at:new Date().toISOString(),chain_id:8453,user,pool:POOL,data_provider:DATA_PROVIDER,oracle:ORACLE,rpc:b.url,base_currency_unit_raw:baseUnit.toString(),account:{total_collateral_base_raw:account.total_collateral_base.toString(),total_debt_base_raw:account.total_debt_base.toString(),health_factor_1e18:account.health_factor.toString(),health_factor:Number(account.health_factor)/1e18,liquidatable:account.health_factor>0n&&account.health_factor<1000000000000000000n},reserve_count:reserves.length,positions,debts,collaterals,simulation_status:'NOT_RUN',execution_allowed:false,rule:'Reserve legs are observed state only. No route is executable until debtToCover, seized collateral, swap output, flash premium, L2 gas, L1 data fee and atomic eth_call/eth_simulate pass.',elapsed_ms:Date.now()-started});}catch(e){res.status(502).json({ok:false,error:String(e?.message||e),observed_at:new Date().toISOString(),elapsed_ms:Date.now()-started});}}