import crypto from 'node:crypto';

const BASE={chainId:8453,rpc:['https://mainnet-preconf.base.org','https://mainnet.base.org','https://base-rpc.publicnode.com'],aavePool:'0xA238Dd80C259a72e81d7e4664a9801593F98d1c5'};
const CHAINS={base:BASE.rpc,ethereum:['https://ethereum-rpc.publicnode.com','https://eth.llamarpc.com'],arbitrum:['https://arbitrum-one-rpc.publicnode.com','https://arb1.arbitrum.io/rpc']};
const BORROW_TOPIC='0xb3d084820fb1a9decffb176436bd02558d15fac9b0ddfed8c465bc7359d7dce0';
const USER_SEL='bf92857c';
const FLASH_PREMIUM_TOTAL='0x074b2e43';

function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v;}
function evidence(kind,payload,meta={}){const observed_at=new Date().toISOString();const canonical=JSON.stringify(stable({kind,observed_at,payload,meta}));return{kind,observed_at,payload,meta,evidence_sha256:crypto.createHash('sha256').update(canonical).digest('hex')};}
function encAddress(addr){const h=String(addr).toLowerCase().replace(/^0x/,'');if(!/^[0-9a-f]{40}$/.test(h))throw new Error('invalid EVM address');return h.padStart(64,'0');}
function words(data){const h=String(data||'0x').replace(/^0x/,'');const out=[];for(let i=0;i+64<=h.length;i+=64)out.push(BigInt('0x'+h.slice(i,i+64)));return out;}
function decodeAccount(data){const w=words(data);if(w.length<6)throw new Error('short getUserAccountData response');return{total_collateral_base:w[0].toString(),total_debt_base:w[1].toString(),available_borrows_base:w[2].toString(),liquidation_threshold_bps:Number(w[3]),ltv_bps:Number(w[4]),health_factor_raw:w[5].toString(),health_factor:Number(w[5])/1e18};}
function borrower(log){const t=log?.topics||[];if(t.length<3)return null;const h=String(t[2]).replace(/^0x/,'');return h.length===64?'0x'+h.slice(-40).toLowerCase():null;}
function hexInt(x){return Number(BigInt(x));}
function blockHex(n){return'0x'+Number(n).toString(16);}
function clamp(v,d,min,max){const n=parseInt(v??'',10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):d;}

async function post(url,payload,timeout=9000){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),timeout);const t0=Date.now();try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','user-agent':'flashbot-cloud-v5'},body:JSON.stringify(payload),signal:ctl.signal,cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();return{j,latency_ms:Date.now()-t0};}finally{clearTimeout(timer);}}
async function rpcAny(urls,method,params=[],timeout=9000){const errors=[];for(const url of urls){try{const{j,latency_ms}=await post(url,{jsonrpc:'2.0',id:1,method,params},timeout);if(j?.error)throw new Error(j.error.message||JSON.stringify(j.error));return{result:j?.result,url,latency_ms};}catch(e){errors.push({url,error:String(e?.message||e)});}}const x=new Error('all RPCs failed');x.details=errors;throw x;}
async function rpcBatch(url,calls,timeout=15000){const payload=calls.map((c,i)=>({jsonrpc:'2.0',id:i+1,method:c.method,params:c.params||[]}));const{j,latency_ms}=await post(url,payload,timeout);if(!Array.isArray(j))throw new Error('batch response not array');const by=new Map(j.map(x=>[x.id,x]));return{responses:calls.map((_,i)=>by.get(i+1)||{error:{message:'missing response'}}),latency_ms};}
async function accountData(user,tag='latest'){const r=await rpcAny(BASE.rpc,'eth_call',[{to:BASE.aavePool,data:'0x'+USER_SEL+encAddress(user)},tag]);return{user:user.toLowerCase(),...decodeAccount(r.result),rpc:r.url,latency_ms:r.latency_ms};}
async function batchAccounts(users,tag='latest'){const calls=users.map(u=>({method:'eth_call',params:[{to:BASE.aavePool,data:'0x'+USER_SEL+encAddress(u)},tag]}));const errors=[];for(const url of BASE.rpc){try{const b=await rpcBatch(url,calls);return users.map((u,i)=>{const x=b.responses[i];if(!x||x.error||!x.result)return{user:u,ok:false,error:x?.error?.message||'missing'};try{return{user:u,ok:true,...decodeAccount(x.result),rpc:url,latency_ms:b.latency_ms};}catch(e){return{user:u,ok:false,error:String(e?.message||e)};}});}catch(e){errors.push({url,error:String(e?.message||e)});}}const x=new Error('batch accounts failed');x.details=errors;throw x;}
async function flashPremium(){const r=await rpcAny(BASE.rpc,'eth_call',[{to:BASE.aavePool,data:FLASH_PREMIUM_TOTAL},'latest']);const w=words(r.result);return{bps:w.length?Number(w[0]):null,rpc:r.url,latency_ms:r.latency_ms};}

async function live(){const chains={};await Promise.all(Object.entries(CHAINS).map(async([name,urls])=>{try{const[c,b,g]=await Promise.all([rpcAny(urls,'eth_chainId'),rpcAny(urls,'eth_blockNumber'),rpcAny(urls,'eth_gasPrice')]);chains[name]={ok:true,chain_id:hexInt(c.result),block:hexInt(b.result),gas_wei:BigInt(g.result).toString(),rpc:b.url,latency_ms:Math.max(c.latency_ms,b.latency_ms,g.latency_ms)};}catch(e){chains[name]={ok:false,error:String(e?.message||e),details:e?.details||null};}}));return evidence('live_chain_health',{ok:true,agent:'FLASHBOT-CLOUD-V5.1',mode:'READ_ONLY',chains,execution_allowed:false});}
async function verifyUser(q){const user=String(q.user||q.address||'').toLowerCase();if(!/^0x[0-9a-f]{40}$/.test(user))return evidence('aave_user_verify',{ok:false,error:'valid user/address required'});const[a,p]=await Promise.all([accountData(user),flashPremium()]);const liquidatable=a.total_debt_base!=='0'&&a.health_factor>0&&a.health_factor<1;return evidence('aave_user_verify',{ok:true,chain_id:BASE.chainId,pool:BASE.aavePool,user,account:a,flash_loan_premium_bps:p.bps,liquidatable_now:liquidatable,verdict:liquidatable?'LIQUIDATABLE_NEEDS_PROFIT_SIMULATION':'NOT_LIQUIDATABLE',execution_allowed:false},{rule:'HF is direct Aave Pool.getUserAccountData. Profitability is not inferred from HF.'});}
async function aaveScan(q){const started=Date.now();const lookback=clamp(q.lookback||q.blocks,3000,100,12000);const maxUsers=clamp(q.max_users||q.maxUsers,100,5,250);const head=await rpcAny(BASE.rpc,'eth_blockNumber');const block=hexInt(head.result);const from=Math.max(0,block-lookback+1);const logs=[];for(let b=from;b<=block;b+=1200){const e=Math.min(block,b+1199);const r=await rpcAny(BASE.rpc,'eth_getLogs',[{address:BASE.aavePool,fromBlock:blockHex(b),toBlock:blockHex(e),topics:[BORROW_TOPIC]}],12000);logs.push(...(r.result||[]));}const last=new Map();for(const g of logs){const u=borrower(g);if(!u)continue;const bn=hexInt(g.blockNumber||'0x0');if(bn>=(last.get(u)||0))last.set(u,bn);}const users=[...last.entries()].sort((a,b)=>b[1]-a[1]).slice(0,maxUsers).map(x=>x[0]);const rows=[];for(let i=0;i<users.length;i+=40)rows.push(...await batchAccounts(users.slice(i,i+40)));const valid=rows.filter(x=>x.ok&&Number.isFinite(x.health_factor)&&x.total_debt_base!=='0').sort((a,b)=>a.health_factor-b.health_factor);const liquidatable=valid.filter(x=>x.health_factor>0&&x.health_factor<1);const p=await flashPremium();return evidence('aave_base_recent_borrower_scan',{ok:true,agent:'FLASHBOT-CLOUD-V5.1',mode:'READ_ONLY',chain_id:BASE.chainId,pool:BASE.aavePool,head_block:block,from_block:from,lookback_blocks:lookback,borrow_logs:logs.length,unique_recent_borrowers:last.size,accounts_checked:valid.length,accounts_failed:rows.length-valid.length,flash_loan_premium_bps:p.bps,liquidatable_count:liquidatable.length,liquidatable:liquidatable.slice(0,25),near_liquidation:valid.filter(x=>x.health_factor>=1&&x.health_factor<1.08).slice(0,25),lowest_health_factors:valid.slice(0,25),elapsed_ms:Date.now()-started,execution_allowed:false},{coverage:'RECENT_BORROW_EVENTS_ONLY',rule:'HF<1 still requires reserve reconstruction, exact swap quotes, gas/L1 fee, flash premium and atomic simulation before any execution.'});}
function selftest(){const a='0x000000000000000000000000000000000000dead';const cd='0x'+USER_SEL+encAddress(a);const ws=[100n,50n,25n,8000n,7500n,999000000000000000n];const d=decodeAccount('0x'+ws.map(x=>x.toString(16).padStart(64,'0')).join(''));const checks={calldata:cd==='0xbf92857c'+'0'.repeat(24)+'000000000000000000000000000000000000dead',hf:d.health_factor===0.999,borrow_topic:/^0x[0-9a-f]{64}$/.test(BORROW_TOPIC),pool:/^0x[0-9a-fA-F]{40}$/.test(BASE.aavePool)};return evidence('selftest',{ok:Object.values(checks).every(Boolean),checks});}

export default async function handler(req,res){res.setHeader('cache-control','no-store, max-age=0');const op=String(req.query?.op||'index');try{let out;if(op==='live')out=await live();else if(op==='verify_user')out=await verifyUser(req.query||{});else if(op==='aave_scan')out=await aaveScan(req.query||{});else if(op==='selftest')out=selftest();else out=evidence('index',{ok:true,name:'FLASHBOT-CLOUD-V5.1',mode:'READ_ONLY',endpoints:['/api/live','/api/selftest','/api/verify_user?user=0x...','/api/aave_scan?lookback=3000&max_users=100'],execution:false,signing:false,principle:'NO EVIDENCE = NO CLAIM'});res.status(200).json(out);}catch(e){res.status(502).json(evidence('agent_error',{ok:false,op,error:String(e?.message||e),details:e?.details||null}));}}