const C = Object.freeze({
  chain: 'base', chainId: 8453,
  rpc: 'https://mainnet.base.org',
  aavePool: '0xA238Dd80C259a72e81d7e4664a9801593F98d1c5',
  borrowTopic: '0xb3d084820fb1a9decffb176436bd02558d15fac9b0ddfed8c465bc7359d7dce0',
  userDataSel: 'bf92857c', flashPremiumSel: '074b2e43',
  defaultWindow: 1500, chunk: 500, maxBorrowers: 400, concurrency: 20, nearHf: 1.15, timeoutMs: 7000,
});
let rpcId = 0;
async function rpc(method, params = [], timeoutMs = C.timeoutMs) {
  const t = Date.now();
  const r = await fetch(C.rpc, { method:'POST', headers:{'content-type':'application/json','user-agent':'flashbot-cloud-v4'}, body:JSON.stringify({jsonrpc:'2.0',id:++rpcId,method,params}), signal:AbortSignal.timeout(timeoutMs), cache:'no-store' });
  if (!r.ok) throw new Error(`RPC_HTTP_${r.status}:${method}`);
  const j = await r.json(); if (j.error) throw new Error(`RPC_${method}:${j.error.message || JSON.stringify(j.error)}`);
  return { result:j.result, ms:Date.now()-t };
}
const h2n = h => Number(BigInt(h));
const n2h = n => `0x${BigInt(n).toString(16)}`;
function aw(a){ const h=String(a).toLowerCase().replace(/^0x/,''); if(!/^[0-9a-f]{40}$/.test(h)) throw new Error('INVALID_ADDRESS'); return h.padStart(64,'0'); }
function words(x){ const h=String(x||'0x').replace(/^0x/,''); if(!h || h.length%64) return []; const out=[]; for(let i=0;i<h.length;i+=64) out.push(BigInt(`0x${h.slice(i,i+64)}`)); return out; }
async function mapLimit(items, limit, fn){ const out=new Array(items.length); let cursor=0; async function w(){while(true){const i=cursor++;if(i>=items.length)return;out[i]=await fn(items[i],i)}} await Promise.all(Array.from({length:Math.min(limit,items.length)},w));return out; }
function borrower(log){ const t=log?.topics||[]; if(t.length<3)return null; const h=String(t[2]).replace(/^0x/,''); return /^[0-9a-fA-F]{64}$/.test(h)?`0x${h.slice(-40).toLowerCase()}`:null; }
async function userData(user){ const {result,ms}=await rpc('eth_call',[{to:C.aavePool,data:`0x${C.userDataSel}${aw(user)}`},'pending']); const w=words(result); if(w.length<6)throw new Error('BAD_USER_DATA'); return {user,totalCollateralUsd:Number(w[0])/1e8,totalDebtUsd:Number(w[1])/1e8,availableBorrowsUsd:Number(w[2])/1e8,liquidationThresholdBps:Number(w[3]),ltvBps:Number(w[4]),healthFactor:w[5]===(2n**256n-1n)?null:Number(w[5])/1e18,rpcLatencyMs:ms}; }
async function premium(){ const {result,ms}=await rpc('eth_call',[{to:C.aavePool,data:`0x${C.flashPremiumSel}`},'pending']); const w=words(result); if(!w.length)throw new Error('BAD_FLASH_PREMIUM'); return {bps:Number(w[0]),ms}; }
async function scan(windowBlocks=C.defaultWindow){ const head=h2n((await rpc('eth_blockNumber')).result), start=Math.max(0,head-windowBlocks+1), logs=[]; for(let from=start;from<=head;from+=C.chunk){const to=Math.min(head,from+C.chunk-1);const {result}=await rpc('eth_getLogs',[{address:C.aavePool,fromBlock:n2h(from),toBlock:n2h(to),topics:[C.borrowTopic]}],12000);logs.push(...(result||[]));} const seen=new Map();for(const g of logs){const u=borrower(g);if(!u)continue;const b=h2n(g.blockNumber||'0x0');if(b>=(seen.get(u)||0))seen.set(u,b)} const borrowers=[...seen.entries()].sort((a,b)=>b[1]-a[1]).slice(0,C.maxBorrowers).map(([user,lastBorrowBlock])=>({user,lastBorrowBlock})); const states=await mapLimit(borrowers,C.concurrency,async x=>{try{return{...x,...await userData(x.user)}}catch(e){return{...x,error:String(e?.message||e)}}}); const valid=states.filter(x=>Number.isFinite(x.healthFactor)&&x.totalDebtUsd>0).sort((a,b)=>a.healthFactor-b.healthFactor);return{head,start,borrowLogCount:logs.length,uniqueBorrowers:borrowers.length,checked:states.length,errors:states.filter(x=>x.error).length,liquidatable:valid.filter(x=>x.healthFactor<1),near:valid.filter(x=>x.healthFactor>=1&&x.healthFactor<C.nearHf).slice(0,30),lowest:valid.slice(0,30)}; }
function verify(x={}){const hf=Number(x.healthFactor);if(!Number.isFinite(hf))return{status:'REJECT',executable:false,reasons:['HF_UNVERIFIED']};if(hf>=1)return{status:'WATCH',executable:false,reasons:['HF_NOT_LIQUIDATABLE']};const missing=[];for(const [k,label] of [['exactDebtToCoverUsd','DEBT_TO_COVER_MISSING'],['swapOutputUsd','EXACT_SWAP_QUOTE_MISSING'],['flashFeeUsd','FLASH_FEE_MISSING'],['gasUsd','GAS_MISSING']])if(!Number.isFinite(Number(x[k])))missing.push(label);if(x.simulationPass!==true)missing.push('ATOMIC_SIMULATION_NOT_PASS');if(missing.length)return{status:'NEEDS_PROOF',executable:false,reasons:missing};const net=Number(x.swapOutputUsd)-Number(x.exactDebtToCoverUsd)-Number(x.flashFeeUsd)-Number(x.gasUsd)-Number(x.mevBidUsd||0)-Number(x.safetyBufferUsd||0);if(net<=Number(x.minProfitUsd||0))return{status:'REJECT',executable:false,reasons:['NET_PROFIT_GATE_FAILED'],netProfitUsd:net};return{status:'SIM_PASS',executable:false,reasons:['LIVE_SIGNING_DISABLED'],netProfitUsd:net};}
function dashboard(){return `<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>Flashbot Cloud v4</title><style>body{font-family:system-ui;background:#090d13;color:#edf2f7;padding:16px;margin:0}.c{background:#111824;border:1px solid #263247;border-radius:14px;padding:14px;margin:12px 0}pre{white-space:pre-wrap;word-break:break-word;font-size:12px}.g{color:#5ee79a}.r{color:#ff7b7b}</style><h2>Flashbot Cloud v4 · Proof First</h2><div class=c><b>Chain health</b><pre id=h>loading…</pre></div><div class=c><b>Aave liquidation radar</b><pre id=a>loading…</pre></div><script>async function j(u){let r=await fetch(u,{cache:'no-store'});return r.json()}async function t(){try{let x=await j('/api/health');h.className=x.ok?'g':'r';h.textContent=JSON.stringify(x,null,2)}catch(e){h.textContent=e}try{let x=await j('/api/aave?blocks=1200');a.className=x.ok?'g':'r';a.textContent=JSON.stringify({ok:x.ok,head:x.head,logs:x.borrowLogCount,checked:x.checked,liquidatable:x.liquidatable?.slice(0,10),near:x.near?.slice(0,10),errors:x.errors,observedAt:x.observedAt},null,2)}catch(e){a.textContent=e}}t();setInterval(t,15000)</script>`}
export default async function handler(req,res){res.setHeader('cache-control','no-store');const path=new URL(req.url,'http://x').pathname,at=new Date().toISOString();try{if(path==='/'||path==='/api/dashboard'){res.setHeader('content-type','text/html; charset=utf-8');return res.status(200).send(dashboard())}if(path==='/api/health'){const [ch,b,g,p]=await Promise.all([rpc('eth_chainId'),rpc('eth_blockNumber'),rpc('eth_gasPrice'),premium()]);const chainId=h2n(ch.result);return res.status(chainId===C.chainId?200:502).json({ok:chainId===C.chainId,mode:'READ_ONLY_PROOF_FIRST',chain:C.chain,chainId,blockNumber:h2n(b.result),gasPriceWei:BigInt(g.result).toString(),aaveFlashPremiumBps:p.bps,rpcLatencyMs:{chain:ch.ms,block:b.ms,gas:g.ms,premium:p.ms},signingEnabled:false,broadcastEnabled:false,observedAt:at})}if(path==='/api/aave'){const q=new URL(req.url,'http://x').searchParams,raw=Number(q.get('blocks')||C.defaultWindow),window=Math.max(250,Math.min(12000,Number.isFinite(raw)?raw:C.defaultWindow));return res.status(200).json({ok:true,type:'AAVE_LIQUIDATION_RADAR_V4',chain:'base',observedAt:at,...await scan(window),proofRule:'HF<1 + exact quote + gas + atomic simulation required.'})}if(path==='/api/verify'){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST_ONLY'});return res.status(200).json({ok:true,verification:verify(req.body||{}),observedAt:at})}return res.status(404).json({ok:false,error:'NOT_FOUND'});}catch(e){return res.status(502).json({ok:false,error:String(e?.message||e),observedAt:at})}}
