import base64, hashlib, json, os, sys, time, traceback, urllib.request
from pathlib import Path

ROOT=Path(__file__).resolve().parent
STATE=ROOT/"daemon_state.json"
URL="https://raw.githubusercontent.com/8hatay9-commits/ibo/ad31b08280dbea26ad68454a3d45c20fe3cdaf48/flashbot/releases/v3.9.0/daemon.py"
BLOB_SHA1="67289d1f38bd3e4db9580948b02319436d78fd19"

def diag(obj):
    tmp=STATE.with_name(f"{STATE.name}.{os.getpid()}.v398.tmp")
    tmp.write_text(json.dumps(obj,indent=2),encoding="utf-8")
    tmp.replace(STATE)

worker="--worker" in sys.argv
if worker:
    diag({"ok":False,"version":"FLASHBOT-PRODUCTION-V3.9.8","mode":"DRY_RUN_ONLY","phase":"wrapper_worker_boot","last_error":None,"timestamp":time.time()})

try:
    raw=urllib.request.urlopen(URL,timeout=30).read()
    got=hashlib.sha1(f"blob {len(raw)}\\0".encode()+raw).hexdigest()
    if got!=BLOB_SHA1: raise RuntimeError(f"pinned V3.9.0 daemon mismatch: {got}")
    src=raw.decode("utf-8")
    src=src.replace("FLASHBOT-PRODUCTION-V3.8.4","FLASHBOT-PRODUCTION-V3.9.8")
    src=src.replace("FLASHBOT-SUPERVISOR-V3.8.4","FLASHBOT-SUPERVISOR-V3.9.8")
    old=base64.b64decode("ICAgIHJldHVybiBzcmMKCmRlZiBydW5fd29ya2VyKCk6Cg==").decode("utf-8")
    new=base64.b64decode("ICAgIGltcG9ydCBiYXNlNjQgYXMgX2I2NF9wYXRjaF92Mzk4CiAgICBfb2xkX25lc3RlZD1fYjY0X3BhdGNoX3YzOTguYjY0ZGVjb2RlKCJjM0pqUFhOeVl5NXljM0JzYVhRb2JXRnlhMlZ5TERFcFd6QmRDblk5ZXlKZlgyNWhiV1ZmWHlJNkltWnNZWE5vWW05MFgzWXpObDlqYjNKbElpd2lYMTltYVd4bFgxOGlPbDlmWm1sc1pWOWZmUXBsZUdWaktHTnZiWEJwYkdVb2MzSmpMRU5QVWtWZlZWSk1MQ0psZUdWaklpa3NkaWs9IikuZGVjb2RlKCJ1dGYtOCIpCiAgICBfbmV3X25lc3RlZD1fYjY0X3BhdGNoX3YzOTguYjY0ZGVjb2RlKCJjM0pqUFhOeVl5NXljM0JzYVhRb2JXRnlhMlZ5TERFcFd6QmRDbWx0Y0c5eWRDQmlZWE5sTmpRZ1lYTWdYMkkyTkY5Mk16azRDbDl2YkdSZmNISnZZbVZmZGpNNU9EMWZZalkwWDNZek9UZ3VZalkwWkdWamIyUmxLQ0pqVjA1dFdqRnphV05JU25aWmJWWm1ZekpzTmxwWVRtWmhTRlowV1ZjMGFWaFVNV0pOVkVGM1dGRTlQU0lwTG1SbFkyOWtaU2dpZFhSbUxUZ2lLUXBmYm1WM1gzQnliMkpsWDNZek9UZzlYMkkyTkY5Mk16azRMbUkyTkdSbFkyOWtaU2dpWTFkT2JWb3hjMmxqU0VwMldXMVdabU15YkRaYVdFNW1ZVWhXZEZsWE5HbFlWREZpVFdwVmMwMVVRWGRZVVQwOUlpa3VaR1ZqYjJSbEtDSjFkR1l0T0NJcENtbG1JRjl2YkdSZmNISnZZbVZmZGpNNU9DQnViM1FnYVc0Z2MzSmpPaUJ5WVdselpTQlNkVzUwYVcxbFJYSnliM0lvSWxZekxqa3VPQ0J1WlhOMFpXUWdjSEp2WW1VdGMybDZaU0J0WVhKclpYSWdibTkwSUdadmRXNWtJaWtLYzNKalBYTnlZeTV5WlhCc1lXTmxLRjl2YkdSZmNISnZZbVZmZGpNNU9DeGZibVYzWDNCeWIySmxYM1l6T1Rnc01Ta0tYMjlzWkY5eVlXNXJYM1l6T1RnOVgySTJORjkyTXprNExtSTJOR1JsWTI5a1pTZ2lTVU5CWjBsSVNtaGliWFJzV2tReGVtSXpTakJhVjFGdldUSkdkVnBETlRKWlYzZ3hXbGhOYjB0VGVISmFXR3M1V1ZkT01HRllXbkJrU0d4bVl6Sk9kbU50VlhCRFp6MDlJaWt1WkdWamIyUmxLQ0oxZEdZdE9DSXBDbDl1WlhkZmNtRnVhMTkyTXprNFBWOWlOalJmZGpNNU9DNWlOalJrWldOdlpHVW9Ja2xEUVdkSlNGSjVZVlk1ZVZsWE5YSmFWMUU1WXpJNWVXUkhWbXRMUm5ScVNVZGFkbU5wUW1wSlIyeDFTVWRPYUdKdFVYVmtiVVp6WkZkV2VrdERhMmRoVjFsbldURnphV0V5YkhWYVEwcGtVRlF3YVdSSVNuQlpWelZ1WWtkVmFWaFRlSEphV0dzNVdWZE9NR0ZZV25Ca1NHeG1ZekpPZG1OdFZYQkRhVUZuU1VOQ01HUXlPV1pqYlVaMVlUSldhMUJZVG5aamJsSnNXa05vWWxsNVFtMWlNMGxuV1hsQ2NHSnBRbXBaVnpWclRHNWFhR0pJVm14amVXZHdTVWRzYlVsSFRtSkpiWFJ3WW0xUmFWaFVNRGxKYWtwM1lqSTVjMGxzTUhOaE1sWTFVRmRHYW1SSGJESmhXRkkxV0ROT2FtSXpTbXhMVVc5blNVTkJaMk50Um5WaE1sWnJVRlowWkVOcFFXZEpRMEp0WWpOSloyRlRRbkJpYVVKNVdWYzFibHBUYUhSWldHZHZZa2RXZFV0SVVubGhWamw1V1ZjMWNscFhVWEJNUjNoc1ltbG9NR1F5T1daamJVWjFZVEpXYTB0VGEzQlBaMjluU1VOQlowbERRV2RKUjJ4dFNVZHJPR0pIVm5WTFNGSjVZVlk1ZVZsWE5YSmFWMUZ3VDJsQ2VWbFhOWEphVjFGMVdWaENkMXBYTld0TFNGSjVZVlk1ZVZsWE5YSmFWMUppWVZZd2NFTnBRV2RKUTBGblNVTkJaMkZYV1dkaFZIaHpXbGMwYjJSSVpIWllNMHBvWW0xMGJGcERhelpKU0Vwb1ltMTBiRnBETldoalNFSnNZbTFSYjJSSVpIWllNMHBvWW0xMGJGcEdkSEJZVTJ0TElpa3VaR1ZqYjJSbEtDSjFkR1l0T0NJcENtbG1JRjl2YkdSZmNtRnVhMTkyTXprNElHNXZkQ0JwYmlCemNtTTZJSEpoYVhObElGSjFiblJwYldWRmNuSnZjaWdpVmpNdU9TNDRJRzVsYzNSbFpDQmlZV3hoYm1ObFpDMXlZVzVyYVc1bklHMWhjbXRsY2lCdWIzUWdabTkxYm1RaUtRcHpjbU05YzNKakxuSmxjR3hoWTJVb1gyOXNaRjl5WVc1clgzWXpPVGdzWDI1bGQxOXlZVzVyWDNZek9UZ3NNU2tLWDI5c1pGOXdiMnhwWTNsZmRqTTVPRDFmWWpZMFgzWXpPVGd1WWpZMFpHVmpiMlJsS0NKSlEwRm5TVWhPTUZkNVNubGlNMVl3V2xZNWFsbFhOV3RoVjFKb1pFZFdlbGd5ZUdoak0xSm1XVzFHTUZreVoybFlWREZ6V2xjMGIyTnRSblZoTWxaclMxRnZaMGxEUVdkak0xSmlTVzFPYUdKdFVuQmFSMFl3V2xZNWQySXllSEJaTTJ0cFdGUXdhVlpyUmsxV1ZWWm1VbXRzVTFVeFVtWlJWVTVWVTFaYVNsWkdiR1pWYTBaUFV6QldSVmd4V1hwT2FVbExJaWt1WkdWamIyUmxLQ0oxZEdZdE9DSXBDbDl1WlhkZmNHOXNhV041WDNZek9UZzlYMkkyTkY5Mk16azRMbUkyTkdSbFkyOWtaU2dpU1VOQlowbElUakJYZVVwNVlqTldNRnBXT1dwWlZ6VnJZVmRTYUdSSFZucFlNbmhvWXpOU1psbHRSakJaTW1kcFdGUXhjMXBYTkc5amJVWjFZVEpXYTB0UmIyZEpRMEZuWXpOU1lrbHVVbmxoVjBaMVdqSjRiRmd5VG1oaWJWSndXa2RHTUZwWVRtWmlSMFo2WkVZNWFWbFlVbXBoUTBwa1VGZDRiR0pwYURCamJXeG1ZMjFHZFdFeVZtdExVVzluU1VOQloyTXpVbUpKYmxJellqRTVkMkl5T1hOWU1rNW9ZbTFTY0ZwSFJqQmFXRTVtWWtkR2VtUkdPV2xaV0ZKcVlVTktaRkJYZUd4aWFXZ3daREk1Wm1OdFJuVmhNbFpyUzFGdlowbERRV2RqTTFKaVNXMU9hR0p0VW5CYVIwWXdXbFk1ZDJJeWVIQlpNMnRwV0ZRd2FWRldTa05ZTUVwQ1ZFVkdUMUV3VmtWWU1WSlRVMVk0ZVZWRk9WQlVSamxYVFhwck5FbG5iejBpS1M1a1pXTnZaR1VvSW5WMFppMDRJaWtLYVdZZ1gyOXNaRjl3YjJ4cFkzbGZkak01T0NCdWIzUWdhVzRnYzNKak9pQnlZV2x6WlNCU2RXNTBhVzFsUlhKeWIzSW9JbFl6TGprdU9DQnVaWE4wWldRZ2NHOXNhV041SUcxaGNtdGxjaUJ1YjNRZ1ptOTFibVFpS1FwemNtTTljM0pqTG5KbGNHeGhZMlVvWDI5c1pGOXdiMnhwWTNsZmRqTTVPQ3hmYm1WM1gzQnZiR2xqZVY5Mk16azRMREVwQ25ZOWV5SmZYMjVoYldWZlh5STZJbVpzWVhOb1ltOTBYM1l6Tmw5amIzSmxJaXdpWDE5bWFXeGxYMThpT2w5ZlptbHNaVjlmZlFwbGVHVmpLR052YlhCcGJHVW9jM0pqTEVOUFVrVmZWVkpNTENKbGVHVmpJaWtzZGlrPSIpLmRlY29kZSgidXRmLTgiKQogICAgaWYgX29sZF9uZXN0ZWQgbm90IGluIHNyYzoKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoIlYzLjkuOCBWMy43IG5lc3RlZC1jb3JlIG1hcmtlciBub3QgZm91bmQiKQogICAgc3JjPXNyYy5yZXBsYWNlKF9vbGRfbmVzdGVkLF9uZXdfbmVzdGVkLDEpCiAgICByZXR1cm4gc3JjCgpkZWYgcnVuX3dvcmtlcigpOgo=").decode("utf-8")
    if old not in src: raise RuntimeError("V3.9.8 patch_core return marker not found")
    src=src.replace(old,new,1)
    compile(src,URL,"exec")
    exec(compile(src,URL,"exec"),{"__name__":"__main__","__file__":str(Path(__file__).resolve())})
except BaseException as e:
    if worker:
        try:
            diag({"ok":False,"version":"FLASHBOT-PRODUCTION-V3.9.8","mode":"DRY_RUN_ONLY","phase":"wrapper_worker_error","last_error":f"{type(e).__name__}:{e}","traceback_tail":traceback.format_exc()[-4000:],"timestamp":time.time()})
        except Exception: pass
    raise
