package com.ibo.smartremote;

import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import android.graphics.drawable.*;import android.content.*;import android.hardware.ConsumerIrManager;import android.net.*;import android.net.wifi.WifiManager;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(7,17,25));getWindow().setNavigationBarColor(Color.rgb(7,17,25));setContentView(new RemoteView(this));}
}

class RemoteView extends View{
 enum S{HOME,TV,CLIMATE,SCAN,BRANDS,SCENES,SETTINGS}
 final Paint p=new Paint(3),st=new Paint(3); final int BG=Color.rgb(5,14,21),CARD=Color.rgb(18,31,40),CARD2=Color.rgb(23,39,49),BORDER=Color.rgb(45,62,73),WHITE=Color.rgb(246,250,252),MUTED=Color.rgb(150,167,178),BLUE=Color.rgb(44,182,255),GREEN=Color.rgb(42,215,170); final Context ctx; final ConsumerIrManager ir; final Handler h=new Handler(Looper.getMainLooper()); S s=S.HOME; float sc=1,ox,oy; int temp=24; String brand="Samsung",toast=""; long toastUntil; boolean scanning=false; final ArrayList<String> found=new ArrayList<>();
 RemoteView(Context c){super(c);ctx=c;ir=(ConsumerIrManager)c.getSystemService(Context.CONSUMER_IR_SERVICE);st.setStyle(Paint.Style.STROKE);st.setStrokeCap(Paint.Cap.ROUND);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
 boolean hasIr(){return ir!=null&&ir.hasIrEmitter();}
 boolean wifi(){ConnectivityManager cm=(ConnectivityManager)ctx.getSystemService(Context.CONNECTIVITY_SERVICE);if(cm==null)return false;Network n=cm.getActiveNetwork();NetworkCapabilities cap=n==null?null:cm.getNetworkCapabilities(n);return cap!=null&&cap.hasTransport(NetworkCapabilities.TRANSPORT_WIFI);}
 String cap(){if(wifi()&&hasIr())return"WiFi + IR hazır";if(wifi())return"WiFi hazır • IR yok";if(hasIr())return"Çevrimdışı IR hazır";return"WiFi kapalı • IR yok";}
 @Override protected void onDraw(Canvas c){super.onDraw(c);sc=Math.min(getWidth()/390f,getHeight()/844f);ox=(getWidth()-390*sc)/2;oy=(getHeight()-844*sc)/2;c.drawColor(BG);c.save();c.translate(ox,oy);c.scale(sc,sc);p.setShader(new LinearGradient(0,0,390,844,Color.rgb(9,25,35),BG,Shader.TileMode.CLAMP));c.drawRect(0,0,390,844,p);p.setShader(null);switch(s){case HOME:home(c);break;case TV:tv(c);break;case CLIMATE:climate(c);break;case SCAN:scan(c);break;case BRANDS:brands(c);break;case SCENES:scenes(c);break;case SETTINGS:settings(c);break;}if(System.currentTimeMillis()<toastUntil)toast(c);c.restore();if(scanning)postInvalidateDelayed(40);}
 void text(Canvas c,String t,float x,float y,float z,int col,Paint.Align a,boolean b){p.setColor(col);p.setTextSize(z);p.setTextAlign(a);p.setTypeface(Typeface.create("sans",b?1:0));c.drawText(t,x,y,p);}
 void card(Canvas c,float x,float y,float w,float h,float r){p.setColor(CARD);p.setShadowLayer(8,0,4,0x66000000);c.drawRoundRect(x,y,x+w,y+h,r,r,p);p.clearShadowLayer();st.setColor(BORDER);st.setStrokeWidth(1);c.drawRoundRect(x,y,x+w,y+h,r,r,st);}
 void pill(Canvas c,float x,float y,float w,float h,String t,boolean a){p.setColor(a?BLUE:CARD2);c.drawRoundRect(x,y,x+w,y+h,h/2,h/2,p);text(c,t,x+w/2,y+h/2+4,11,a?Color.rgb(3,25,34):WHITE,Paint.Align.CENTER,true);}
 void circle(Canvas c,float x,float y,float r,String t,boolean a){p.setColor(a?Color.rgb(16,76,109):CARD2);c.drawCircle(x,y,r,p);st.setColor(BORDER);st.setStrokeWidth(1);c.drawCircle(x,y,r,st);text(c,t,x,y+6,18,a?BLUE:WHITE,Paint.Align.CENTER,true);}
 void back(Canvas c){text(c,"‹",24,68,34,WHITE,Paint.Align.CENTER,false);}
 void top(Canvas c,String title){text(c,"9:41",22,28,12,WHITE,Paint.Align.LEFT,true);back(c);text(c,title,195,70,18,WHITE,Paint.Align.CENTER,true);}
 void nav(Canvas c,int a){p.setColor(Color.rgb(7,17,24));c.drawRect(0,706,390,844,p);String[] i={"⌂","▣","◇","⚙"},n={"Ana Sayfa","Cihazlar","Sahneler","Ayarlar"};for(int k=0;k<4;k++){float x=49+k*97;int co=k==a?BLUE:MUTED;text(c,i[k],x,746,22,co,Paint.Align.CENTER,false);text(c,n[k],x,774,10,co,Paint.Align.CENTER,k==a);}}
 void home(Canvas c){text(c,"9:41",22,28,12,WHITE,Paint.Align.LEFT,true);text(c,"SmartRemote",22,73,22,WHITE,Paint.Align.LEFT,true);text(c,"Hoş geldin!",22,95,12,MUTED,Paint.Align.LEFT,false);circle(c,322,72,19,"⌕",false);circle(c,365,72,19,"⚙",false);String[]t={"Tümü","TV","Klima","Ses","Diğer"};float x=20;for(int k=0;k<t.length;k++){float w=k==0?66:k==2?61:55;pill(c,x,114,w,36,t[k],k==0);x+=w+7;}homeCard(c,20,166,"▱","TV","Televizyon");homeCard(c,200,166,"▭","Klima","İklimlendirme");homeCard(c,20,300,"◔","Uydu / Receiver","Alıcı sistemleri");homeCard(c,200,300,"▥","Ses Sistemi","Hoparlör / AVR");homeCard(c,20,434,"▰","Projeksiyon","Projektörler");homeCard(c,200,434,"⌂","Akıllı Cihazlar","Ev cihazları");card(c,20,572,350,78,20);circle(c,53,611,21,wifi()?"⌁":"×",wifi());text(c,"WiFi & IR Durumu",86,603,15,WHITE,Paint.Align.LEFT,true);text(c,cap(),86,625,12,MUTED,Paint.Align.LEFT,false);nav(c,0);}
 void homeCard(Canvas c,float x,float y,String ic,String t,String sub){card(c,x,y,170,122,18);text(c,ic,x+85,y+48,31,WHITE,Paint.Align.CENTER,false);text(c,t,x+85,y+79,14,WHITE,Paint.Align.CENTER,true);text(c,sub,x+85,y+99,10,MUTED,Paint.Align.CENTER,false);}
 void tv(Canvas c){top(c,brand+" TV");p.setColor(GREEN);c.drawCircle(169,93,4,p);text(c,"Bağlı / Hazır",178,97,11,MUTED,Paint.Align.LEFT,false);float cx=195,cy=240;p.setColor(Color.rgb(27,42,52));c.drawCircle(cx,cy,92,p);p.setColor(Color.rgb(11,22,29));c.drawCircle(cx,cy,37,p);text(c,"OK",cx,cy+6,17,WHITE,Paint.Align.CENTER,true);text(c,"⌃",cx,cy-58,26,WHITE,Paint.Align.CENTER,false);text(c,"⌄",cx,cy+70,26,WHITE,Paint.Align.CENTER,false);text(c,"‹",cx-62,cy+7,34,WHITE,Paint.Align.CENTER,false);text(c,"›",cx+62,cy+7,34,WHITE,Paint.Align.CENTER,false);rocker(c,18,188,"VOL");rocker(c,334,188,"CH");action(c,73,382,"↶","Geri");action(c,195,382,"⌂","Ana Sayfa");action(c,317,382,"☰","Menü");chip(c,22,456,78,"NETFLIX",Color.WHITE,Color.RED);chip(c,108,456,78,"YouTube",Color.WHITE,Color.RED);chip(c,194,456,78,"Disney+",Color.rgb(13,65,150),WHITE);chip(c,280,456,88,"prime video",Color.rgb(18,166,226),WHITE);pill(c,31,536,88,48,"123",false);pill(c,151,536,88,48,"MUTE",false);pill(c,271,536,88,48,"Kaynak",false);card(c,20,610,350,70,18);text(c,"Kontrol kanalı",36,636,12,MUTED,Paint.Align.LEFT,false);text(c,cap(),36,659,15,WHITE,Paint.Align.LEFT,true);text(c,"IR",337,652,12,hasIr()?GREEN:MUTED,Paint.Align.CENTER,true);}
 void rocker(Canvas c,float x,float y,String l){card(c,x,y,38,115,19);text(c,"+",x+19,y+27,24,WHITE,Paint.Align.CENTER,false);text(c,l,x+19,y+59,11,MUTED,Paint.Align.CENTER,true);text(c,"−",x+19,y+95,24,WHITE,Paint.Align.CENTER,false);}
 void action(Canvas c,float x,float y,String i,String l){circle(c,x,y,26,i,false);text(c,l,x,y+49,11,MUTED,Paint.Align.CENTER,false);}
 void chip(Canvas c,float x,float y,float w,String l,int bg,int fg){p.setColor(bg);c.drawRoundRect(x,y,x+w,y+45,10,10,p);text(c,l,x+w/2,y+28,l.length()>8?10:12,fg,Paint.Align.CENTER,true);}
 void climate(Canvas c){top(c,"Daikin Klima");p.setColor(GREEN);c.drawCircle(173,93,4,p);text(c,"Bağlı",182,97,11,MUTED,Paint.Align.LEFT,false);RectF a=new RectF(70,135,320,385);st.setStrokeWidth(14);st.setColor(Color.rgb(56,73,84));c.drawArc(a,195,150,false,st);st.setColor(BLUE);c.drawArc(a,195,120,false,st);text(c,""+temp,190,278,55,WHITE,Paint.Align.CENTER,true);text(c,"°C",235,254,17,WHITE,Paint.Align.LEFT,true);text(c,"❄  Soğutma",195,316,13,BLUE,Paint.Align.CENTER,true);circle(c,72,348,23,"−",false);circle(c,318,348,23,"+",false);String[]m={"Soğutma","Isıtma","Fan","Nem Alma"};for(int k=0;k<4;k++){float x=20+k*88;card(c,x,397,82,80,14);text(c,k==0?"❄":k==1?"☀":k==2?"◉":"◊",x+41,430,23,k==0?WHITE:MUTED,Paint.Align.CENTER,false);text(c,m[k],x+41,459,10,k==0?BLUE:WHITE,Paint.Align.CENTER,true);}String[]b={"Otomatik","Uyku","Turbo","Zamanlayıcı"};for(int k=0;k<4;k++){float x=20+k*88;card(c,x,497,82,76,14);text(c,k==0?"A":k==1?"☾":k==2?"◉":"◷",x+41,529,20,WHITE,Paint.Align.CENTER,true);text(c,b[k],x+41,554,9,MUTED,Paint.Align.CENTER,false);}card(c,20,602,350,72,18);text(c,"Klima kontrolü",36,630,12,MUTED,Paint.Align.LEFT,false);text(c,hasIr()?"IR vericisi bulundu":"IR yok • WiFi cihazı seçilebilir",36,653,14,WHITE,Paint.Align.LEFT,true);}
 void scan(Canvas c){top(c,"Cihaz Algılanıyor");text(c,scanning?"Yakındaki cihazlar taranıyor…":"Tarama tamamlandı",195,108,13,MUTED,Paint.Align.CENTER,false);text(c,scanning?"Lütfen bekleyin.":cap(),195,128,11,MUTED,Paint.Align.CENTER,false);float cx=195,cy=245;for(int i=1;i<=4;i++){st.setStrokeWidth(1.2f);st.setColor(Color.rgb(35+i*4,58+i*5,72+i*4));c.drawCircle(cx,cy,i*30,st);}if(scanning){float ang=(System.currentTimeMillis()%3000)/3000f*360;Path q=new Path();q.moveTo(cx,cy);for(int d=0;d<=44;d+=4){double r=Math.toRadians(ang-d);q.lineTo(cx+(float)Math.cos(r)*120,cy+(float)Math.sin(r)*120);}q.close();p.setColor(0x442CB6FF);c.drawPath(q,p);}p.setColor(BLUE);c.drawCircle(cx,cy,5,p);float y=388;if(found.isEmpty()){row(c,y,"Samsung TV","Örnek • tarama sonucunda değişir");row(c,y+64,"LG Klima","Örnek • yerel profil");row(c,y+128,"Sony Ses Sistemi","Örnek • ağ cihazı");}else for(int i=0;i<Math.min(5,found.size());i++)row(c,y+i*64,found.get(i),"Yerel ağda bulundu");nav(c,1);}
 void row(Canvas c,float y,String t,String sub){card(c,20,y,350,57,14);text(c,"▱",44,y+35,22,WHITE,Paint.Align.CENTER,false);text(c,t,68,y+23,13,WHITE,Paint.Align.LEFT,true);text(c,sub,68,y+42,9.5f,MUTED,Paint.Align.LEFT,false);text(c,"✓",345,y+35,20,GREEN,Paint.Align.CENTER,true);}
 void brands(Canvas c){top(c,"Marka Seç");card(c,20,102,350,45,15);text(c,"⌕",40,131,18,MUTED,Paint.Align.CENTER,false);text(c,"Marka ara…",62,130,12,MUTED,Paint.Align.LEFT,false);String[][]br={{"SAMSUNG","LG","SONY"},{"PHILIPS","VESTEL","BEKO"},{"arçelik","TOSHIBA","Panasonic"},{"Daikin","Mitsubishi","BOSCH"},{"SIEMENS","SHARP","Haier"}};float y=170;for(String[]r:br){for(int k=0;k<3;k++){float x=20+k*119;card(c,x,y,112,53,13);text(c,r[k],x+56,y+32,r[k].length()>8?10:13,WHITE,Paint.Align.CENTER,true);}y+=64;}card(c,20,502,350,55,14);text(c,"Tüm Markaları Gör",195,536,13,WHITE,Paint.Align.CENTER,true);text(c,"Profil desteği marka/model protokolüne bağlıdır.",195,594,11,MUTED,Paint.Align.CENTER,false);nav(c,1);}
 void scenes(Canvas c){top(c,"Sahneler");circle(c,360,70,18,"+",false);sceneRow(c,110,"▰","Film Modu","TV, Ses Sistemi, Işıklar");sceneRow(c,180,"☾","Uyku Modu","TV Kapalı, Klima 24°C");sceneRow(c,250,"⌘","Oyun Modu","TV, Ses Sistemi, Konsol");sceneRow(c,320,"●●","Misafir Modu","TV, Uydu, Ses Sistemi");sceneRow(c,390,"▱","Çalışma Modu","Projeksiyon, Işıklar");sceneRow(c,460,"♥","Benim Sahnem","Özel Ayarlar");nav(c,2);}
 void sceneRow(Canvas c,float y,String i,String t,String sub){card(c,20,y,350,58,14);text(c,i,48,y+36,20,WHITE,Paint.Align.CENTER,false);text(c,t,76,y+24,13,WHITE,Paint.Align.LEFT,true);text(c,sub,76,y+43,9.5f,MUTED,Paint.Align.LEFT,false);text(c,"›",344,y+38,24,MUTED,Paint.Align.CENTER,false);}
 void settings(Canvas c){top(c,"Ayarlar");setrow(c,112,"⌁","Bağlantı",cap());setrow(c,184,"IR","Kızılötesi",hasIr()?"Donanım hazır":"Bu telefonda IR vericisi yok");setrow(c,256,"⌕","Cihaz Taraması","SSDP yerel ağ keşfi");setrow(c,328,"▣","Arayüz","SmartRemote koyu premium tema");setrow(c,400,"i","Uygulama","İBO • 1.0.0");card(c,20,500,350,118,18);text(c,"Çevrimdışı çalışma",36,530,14,WHITE,Paint.Align.LEFT,true);text(c,"IR vericili telefonlarda internet gerekmeden TV komutları",36,554,10.5f,MUTED,Paint.Align.LEFT,false);text(c,"gönderilebilir. WiFi cihazları aynı yerel ağda olmalıdır.",36,574,10.5f,MUTED,Paint.Align.LEFT,false);text(c,"Her marka/model için ayrı protokol profili gerekebilir.",36,600,10.5f,MUTED,Paint.Align.LEFT,false);nav(c,3);}
 void setrow(Canvas c,float y,String i,String t,String sub){card(c,20,y,350,58,14);text(c,i,48,y+36,17,BLUE,Paint.Align.CENTER,true);text(c,t,76,y+24,13,WHITE,Paint.Align.LEFT,true);text(c,sub,76,y+43,10,MUTED,Paint.Align.LEFT,false);text(c,"›",347,y+37,24,MUTED,Paint.Align.CENTER,false);}
 void toast(Canvas c){float w=Math.min(340,40+p.measureText(toast));card(c,(390-w)/2,650,w,44,22);text(c,toast,195,678,12,WHITE,Paint.Align.CENTER,true);postInvalidateDelayed(120);}
 void say(String z){toast=z;toastUntil=System.currentTimeMillis()+2200;invalidate();}
 void go(S n){s=n;if(n==S.SCAN)discover();invalidate();}
 void send(String act){if(!hasIr()){say("IR vericisi yok • WiFi cihazı seç");return;}String code=null;if(brand.equals("Samsung")){switch(act){case"POWER":code="E0E040BF";break;case"VU":code="E0E0E01F";break;case"VD":code="E0E0D02F";break;case"CU":code="E0E048B7";break;case"CD":code="E0E008F7";break;case"M":code="E0E0F00F";break;case"S":code="E0E0807F";break;case"U":code="E0E006F9";break;case"D":code="E0E08679";break;case"L":code="E0E0A659";break;case"R":code="E0E046B9";break;case"OK":code="E0E016E9";break;}}else if(brand.equals("LG")){switch(act){case"POWER":code="20DF10EF";break;case"VU":code="20DF40BF";break;case"VD":code="20DFC03F";break;case"CU":code="20DF00FF";break;case"CD":code="20DF807F";break;case"M":code="20DF906F";break;case"S":code="20DFD02F";break;case"U":code="20DF02FD";break;case"D":code="20DF827D";break;case"L":code="20DFE01F";break;case"R":code="20DF609F";break;case"OK":code="20DF22DD";break;}}if(code==null){say("Bu marka/komut için IR profili yok");return;}try{long v=Long.parseUnsignedLong(code,16);int[]a=new int[67];a[0]=brand.equals("Samsung")?4500:9000;a[1]=4500;int q=2;for(int bi=3;bi>=0;bi--){int by=(int)((v>>(bi*8))&255);for(int bit=0;bit<8;bit++){a[q++]=560;a[q++]=((by>>bit)&1)==1?1690:560;}}a[66]=560;ir.transmit(38000,a);say(brand+" • komut gönderildi");}catch(Exception e){say("IR gönderimi başarısız");}}
 void discover(){if(scanning)return;found.clear();scanning=true;new Thread(()->{if(!wifi()){h.post(()->{scanning=false;say("WiFi bağlı değil");});return;}WifiManager.MulticastLock lock=null;DatagramSocket ds=null;try{WifiManager wm=(WifiManager)ctx.getApplicationContext().getSystemService(Context.WIFI_SERVICE);if(wm!=null){lock=wm.createMulticastLock("ibo");lock.setReferenceCounted(false);lock.acquire();}ds=new DatagramSocket();ds.setSoTimeout(500);byte[]b=("M-SEARCH * HTTP/1.1\r\nHOST:239.255.255.250:1900\r\nMAN:\"ssdp:discover\"\r\nMX:2\r\nST:ssdp:all\r\n\r\n").getBytes(StandardCharsets.UTF_8);ds.send(new DatagramPacket(b,b.length,InetAddress.getByName("239.255.255.250"),1900));long end=System.currentTimeMillis()+2400;HashSet<String> seen=new HashSet<>();while(System.currentTimeMillis()<end){try{byte[]buf=new byte[4096];DatagramPacket d=new DatagramPacket(buf,buf.length);ds.receive(d);String ip=d.getAddress().getHostAddress();if(seen.add(ip))h.post(()->{found.add("Ağ Cihazı • "+ip);invalidate();});}catch(SocketTimeoutException e){}}}catch(Exception e){}finally{if(ds!=null)ds.close();if(lock!=null&&lock.isHeld())lock.release();h.post(()->{scanning=false;say(found.isEmpty()?"Cihaz bulunamadı":found.size()+" cihaz bulundu");invalidate();});}},"ibo-scan").start();}
 @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=(e.getX()-ox)/sc,y=(e.getY()-oy)/sc;if(y>706){if(x<97)go(S.HOME);else if(x<195)go(S.SCAN);else if(x<292)go(S.SCENES);else go(S.SETTINGS);return true;}if(x<60&&y<105&&s!=S.HOME){go(S.HOME);return true;}switch(s){case HOME:if(y>150&&y<295)go(x<195?S.TV:S.CLIMATE);else if(y>295&&y<560)go(S.BRANDS);else if(y<110&&x>340)go(S.SETTINGS);break;case TV:tvTouch(x,y);break;case CLIMATE:if(y>315&&y<385){if(x<130)temp=Math.max(16,temp-1);else if(x>260)temp=Math.min(30,temp+1);say(temp+"°C");invalidate();}break;case BRANDS:if(y>=170&&y<=490){String[][]br={{"Samsung","LG","Sony"},{"Philips","Vestel","Beko"},{"Arçelik","Toshiba","Panasonic"},{"Daikin","Mitsubishi","Bosch"},{"Siemens","Sharp","Haier"}};int r=Math.min(4,Math.max(0,(int)((y-170)/64))),co=Math.min(2,Math.max(0,(int)((x-20)/119)));brand=br[r][co];say(brand+" seçildi");go((brand.equals("Daikin")||brand.equals("Mitsubishi"))?S.CLIMATE:S.TV);}break;case SCENES:if(y>100&&y<540)say("Sahne çalıştırıldı");break;case SETTINGS:if(y>245&&y<325)go(S.SCAN);break;default:break;}return true;}
 void tvTouch(float x,float y){float dx=x-195,dy=y-240,r=dx*dx+dy*dy;if(r<1600){send("OK");return;}if(r<10000){send(Math.abs(dx)>Math.abs(dy)?(dx<0?"L":"R"):(dy<0?"U":"D"));return;}if(x<65&&y>180&&y<310){if(y<235)send("VU");else if(y>265)send("VD");return;}if(x>325&&y>180&&y<310){if(y<235)send("CU");else if(y>265)send("CD");return;}if(y>520&&y<600){if(x>130&&x<255)send("M");else if(x>250)send("S");}}
}
